name: Web-TLO Windows Builder
on:
  push:
    tags:
      - "v*.*"

jobs:
  wtlo-win:
    name: wTLO win build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./make-wtlo-win.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.zip
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
          prerelease: true
